#+options: toc:nil

** rgov - Recreation.gov Campground Checker

[[http://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

=rgov= is a program to check for available campsites on
Recreation.gov. It can be used in the terminal, or as a background
daemon, relying on Pushsafer to send a notification to your phone or
other device when a campsite at your desired camground becomes
available.

*** Installation

Requires: Python 3.6+

From pypi:

$ =pip install rgov=

Manually:

$ =git clone https://github.com/jsbmg/rgov=

$ =cd rgov=

$ =pip install . pyproject.toml=

**** Setting up Pushsafer

Rgov uses the Pushsafer API to send push notifications to your device in
the event a campground becomes available. You will need to create an
account, register your device, and save the API key if you want to run
the program as a daemon.

*** Quick Start

After installation, initialize with:

$ =rgov reindex [--with-descriptions]=

Optionally, include the --with-descriptions. This downloads a database
from Recreation.gov containing a database of facilities, which we will
use to lookup campgrounds.

Once that's done, you can use the search command to find your
campground's id (a six-digit number), which we will need to check it for
availability:

$ =rgov search [--descriptions] <campground>=

You can also find the id in the url of the campgound's page on Recreation.gov.

Once you have the idea, you can check the campground for available sites:

$ =rgov check <campground id(s)> --date <mm-dd-yyyy> --length <number of nights>=

If there aren't any sites available where you want to stay, you can use
the daemon command to check for sites while you do other things. Once
you've set up your Pushsafer account, keep your API credentials handy
and run the daemon:

$ =rgov daemon <campground id(s)> --date <...> --length <...> --command <your command>=

Now we will automically check Recreation.gov every five minutes, and
send a notification on Pushsafer if available site(s) exist.

Use the =help= command to get more details about each command.
